[package]
name = "netmgr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
cloudflare = "0.9.1"
envy = "0.4.2"
serde = "1.0.143"
serde_json = "1.0.83"
serde_yaml = "0.9.4"
